-- Phase 2: Add Design System & Mermaid Diagrams support
-- Run this in Supabase SQL Editor after 001_initial_schema.sql

-- Add new columns to documentation table
ALTER TABLE documentation
ADD COLUMN IF NOT EXISTS design JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS clone_prompts JSONB DEFAULT '{}',
ADD COLUMN IF NOT EXISTS mermaid_diagrams JSONB DEFAULT '{}';

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_documentation_design ON documentation((design IS NOT NULL));

-- Add comment
COMMENT ON COLUMN documentation.design IS 'Design system documentation generated by AI';
COMMENT ON COLUMN documentation.clone_prompts IS 'Superprompts for cloning architecture/design/both';
COMMENT ON COLUMN documentation.mermaid_diagrams IS 'Mermaid diagram code for visualizations';

-- Success message
DO $$
BEGIN
    RAISE NOTICE '✅ Phase 2 schema update complete! Design system & diagrams support added.';
END $$;
